# Generated by Django 4.1.7 on 2023-03-10 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_id_profile_name_alter_profile__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
