# Generated by Django 4.1.7 on 2023-03-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile__id_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(default='default.png', upload_to='profileImg'),
        ),
    ]
